version: '3.8'

services:
  hmda_agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - HMDA_API_URL=https://ffiec.cfpb.gov/v2/data-browser-api
    volumes:
      - ./data:/app/data
